version: '3.8'

services:

  pdfservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf_service
    volumes:
      - .:/app
    ports:
      - "8181:80"
    networks:
      mynetwork: {}

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    expose:
      - "9000"
      - "9001"
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      mynetwork: {}

networks:
  mynetwork:
    external: true
    name: ${NETWORK_NAME}
volumes:
  minio_data: